#!/usr/bin/env bash

set -euo pipefail

# Wait for all brokers
for b in 1 2; do
	while ! timeout --kill-after=5 3 kafkacat -b kafka$b:9091 -L &>/dev/null; do
		sleep 1
	done
done

exec java -jar job.jar
